// <auto-generated />
using System;
using FishFarm.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FishFarm.Migrations
{
    [DbContext(typeof(FishFarmDBContext))]
    partial class FishFarmDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FishFarm.Models.Boats", b =>
                {
                    b.Property<int>("BoatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BoatId"));

                    b.Property<string>("BoatName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Boats")
                        .HasColumnType("int");

                    b.Property<int?>("FishFarmsFarmId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<double>("GpsPosition")
                        .HasColumnType("float");

                    b.Property<int>("NoOfCages")
                        .HasColumnType("int");

                    b.HasKey("BoatId");

                    b.HasIndex("Boats");

                    b.HasIndex("FishFarmsFarmId");

                    b.ToTable("Boats");
                });

            modelBuilder.Entity("FishFarm.Models.FishFarms", b =>
                {
                    b.Property<int>("FarmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FarmId"));

                    b.Property<bool>("BargeAvailability")
                        .HasColumnType("bit");

                    b.Property<string>("FarmName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FarmPictureUrl")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FarmId");

                    b.ToTable("FishFarms");
                });

            modelBuilder.Entity("FishFarm.Models.Workers", b =>
                {
                    b.Property<int>("WorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkerId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CertifiedDatePeriod")
                        .HasColumnType("datetime2");

                    b.Property<string>("CrewRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("FishFarmsFarmId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PictureUrl")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WorkerPosition")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("WorkerId");

                    b.HasIndex("FishFarmsFarmId");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("FishFarm.Models.Boats", b =>
                {
                    b.HasOne("FishFarm.Models.FishFarms", null)
                        .WithMany("BoatId")
                        .HasForeignKey("Boats");

                    b.HasOne("FishFarm.Models.FishFarms", "FishFarms")
                        .WithMany()
                        .HasForeignKey("FishFarmsFarmId");

                    b.Navigation("FishFarms");
                });

            modelBuilder.Entity("FishFarm.Models.Workers", b =>
                {
                    b.HasOne("FishFarm.Models.FishFarms", "FishFarms")
                        .WithMany()
                        .HasForeignKey("FishFarmsFarmId");

                    b.Navigation("FishFarms");
                });

            modelBuilder.Entity("FishFarm.Models.FishFarms", b =>
                {
                    b.Navigation("BoatId");
                });
#pragma warning restore 612, 618
        }
    }
}
